Lesson4/Entities/Category.cs
namespace Lesson4.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

Lesson4/Entities/Product.cs
namespace Lesson4.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string?Name { get; set; }
        public decimal Price { get; set; }
    }
}

Lesson4/Models/CategoryListViewModel.cs
using Lesson4.Entities;

namespace Lesson4.Models
{
    public class CategoryListViewModel
    {
        public List<CategoryViewModel> Categories { get; set; }
    }
}

Lesson4/Models/CategoryViewModel.cs
namespace Lesson4.Models
{
    public class CategoryViewModel
    {
        public string Title { get; set; }
    }
}

Lesson4/Models/ErrorViewModel.cs
namespace Lesson4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lesson4/Models/ProductCategoryListViewModel.cs
namespace Lesson4.Models
{
    public class ProductCategoryListViewModel
    {
        public List<ProductViewModel> Products { get; set; }
        public List<CategoryViewModel> Categories { get; set; }
    }
}

Lesson4/Models/ProductViewModel.cs
namespace Lesson4.Models
{
    public class ProductViewModel
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}

Lesson4/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lesson4.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lesson4/Areas/Client/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Lesson4.Areas.Client.Controllers
{
    [Area("Client")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Lesson4/Controllers/HomeController.cs
using Lesson4.Data;
using Lesson4.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lesson4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProductDbContext _context;

        public HomeController(ProductDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var products = _context.Products.Select(p => new ProductViewModel
            {
                Name=p.Name,
                Price=p.Price
            });

            var categories = _context.Categories.Select(c => new CategoryViewModel { Title = c.Name });

            var vm = new ProductCategoryListViewModel
            {
                Products = products.ToList(),
                Categories = categories.ToList()
            };
            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();  
        }
    }
}

Lesson4/ViewComponents/CategoryListViewComponent.cs
using Lesson4.Data;
using Lesson4.Entities;
using Lesson4.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace Lesson4.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private readonly ProductDbContext _context;

        public CategoryListViewComponent(ProductDbContext context)
        {
            _context = context;
        }

        public ViewViewComponentResult Invoke()
        {
            var categories = _context.Categories.Select(c => new CategoryViewModel
            {
                Title = c.Name
            }).ToList();
            var vm = new CategoryListViewModel
            {
                Categories = categories
            };
            return View(vm);
        }
    }
}

Lesson4/Areas/Admin/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<section>
    <h2>Hello Admin Module User</h2>
    <hr style="background-color:springgreen;"/>
</section>

Lesson4/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-primary bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid bg-primary">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Admin Module</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lesson4/Areas/Client/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/Client/Views/Shared/_ClientLayout.cshtml";
}

<section>
    <h2>Hello Client Module User</h2>
    <hr style="background-color:deeppink;" />
</section>

Lesson4/Areas/Client/Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-danger bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid bg-danger">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client Module</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lesson4/Views/Home/Index.cshtml
@model ProductCategoryListViewModel

<h1>Products</h1>
@if (Model.Products != null)
{
    @foreach (var product in Model.Products)
    {
        <h2>Name : @product.Name</h2>
        <h2>Price : $@product.Price</h2>
    }
}

<hr/>

@* <h1>Categories</h1>

@if (Model.Categories != null)
{
    @foreach (var category in Model.Categories)
    {
        <h2>Title : @category.Title</h2>
    }
} *@

Lesson4/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

<section>
    @if (Model.Categories != null)
    {
        <h1>Categories</h1>
        <ul class="list-group">
            @foreach (var item in Model.Categories)
            {
                <li class="list-group-item">@item.Title</li>
            }
        </ul>
    }
</section>

<div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
</div>

Lesson4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lesson4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lesson4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lesson4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-4">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <div class="col-8">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Lesson4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>